### ISSUE TITLE
Problem with webpack loader

### ISSUE THREAD

**Issue by bradleyayers** [tmorin/idomizer#1]
I ran into a problem using the webpack loader — it seems like it's not compiled in the way my setup expected. In `lib/plugins/idomizer-loader.js` I needed to change

``` javascript
exports.default = function (source) {
    this.cacheable();
    var query = _loaderUtils2.default.parseQuery(this.query);
    return (0, _utils.toStringFunction)(source, query);
};
```

to

``` javascript
module.exports = function (source) {
    this.cacheable();
    var query = _loaderUtils2.default.parseQuery(this.query);
    return 'module.exports = ' + (0, _utils.toStringFunction)(source, query);
};
```

Changes:
- `exports.default` → `module.exports`
- prefixing returned string with `'module.exports = ' +`

**Comment by tmorin** [comment]
Thx for the report, I guess idomizer@0.5.2 should fix the problem. I added two example for webpack: the first one with es5 and the other one with es6.
Best regards.

**Comment by bradleyayers** [comment]
Perfect, thanks!
